### ISSUE TITLE
Vytvoriť katalóg požiadaviek

### ISSUE THREAD

**Issue by foldesi2** [TIS2020-FMFI/rampa#14]

**Comment by foldesi2** [comment]
[Katalóg požiadaviek.docx](https://github.com/TIS2020-FMFI/rampa/files/5402526/Katalog.poziadaviek.docx)

**Comment by foldesi2** [comment]
https://drive.google.com/file/d/1ON3yxULrey09XOY_CWPQ_jRzg1crnnvL/view?usp=sharing

**Comment by foldesi2** [comment]
https://drive.google.com/file/d/1ON3yxULrey09XOY_CWPQ_jRzg1crnnvL/view?usp=sharing

**Comment by foldesi2** [comment]
@pavelpetrovic 
Napísal a aktualizoval som katalóg požiadaviek, je na google drive. Prikladám link
https://drive.google.com/file/d/1ON3yxULrey09XOY_CWPQ_jRzg1crnnvL/view?usp=sharing

**Comment by foldesi2** [comment]
@Kirito-chan  vieš prosím ťa skontrolovať ten katalóg ? či je všetko ok.

**Comment by Kirito-chan** [comment]
Dobre skontrolujem

**Comment by Kirito-chan** [comment]
Nuz @foldesi2,  pozeral som to a nesedi tam cislovanie. Je tam dvakrat bod 3.2 . Tiez v obsahu chyba Vstupy softveru co su v dokumente pod 3.4 ale v obsahu nie su, cize treba poposuvat cislovanie v dokumente a do obsahu doplnit aj Vstupy softveru.

Taktiez k tym vstupom co musi zadat uzivatel. Chyba nam tam doplnit aj vychodiskovu/cielovu stanicu a tiez ze v aky den resp. hodinu ma vyrazit z vychodiskovej stanice, lebo nase vypocty (napr. cas) nebude vediet vypocitat na zaklade rychlosti a vzdialenosti, kedze potrebujeme pociatocnu hodinu napr 23:30 kedy ma vyrazit z vycodiskovej stanice.

**Comment by Us3capp** [comment]
Podľa mňa je to dobré :)

**Comment by foldesi2** [comment]
@Kirito-chan Opravil som chyby, už by to malo byt ok :)

**Comment by foldesi2** [comment]
@pavelpetrovic Katalóg požiadaviek je hotový, môžte ho skontrolovať ak budete mat čas, ďakujeme
https://drive.google.com/file/d/1ON3yxULrey09XOY_CWPQ_jRzg1crnnvL/view?usp=sharing

**Comment by pavelpetrovic** [comment]
Vdaka za vybornu pracu s prezentovanim na stretnuti so zadavatelmi.

Skuste, prosim, doplnit katalog poziadaviek a pouzivatelske rozhranie podla toho, co tam odznelo. Ja mam zapisane toto:

1. pridat moznost vyberu kriteria podla ktoreho sa generuje grafikon, aktualne je to startovny cas a den, pridat dalsie dve moznosti: A) koncovy cas a den, B) urceny dodavatel.  Den sa nebude zadavat ako pondelok, utorok a pod. ale kodom, napr. 124 znamena pondelok, utorok a stvrtok.
2. pre blizsie urcenie moznosti B z bodu 1 pridat stlpcek vo vstupnej tabulke, kde by bolo mozne zaskrtnut prave jeden riadok s dodavatelom, ktory ma byt zakladnym kriteriom pre generovanie grafikonu
3. meno dodavatela sa vybera z listboxu, ukaze sa COFOR a meno, ostatne udaje netreba ukazovat v tabulke, budu len v exportovanom exceli
4. pridat samostatne okno, kde je mozne zadavat alebo menit udaje jednotlivych dodavatelov.  do prveho riadku sa napise COFOR, po jeho zadani sa tabulka vyplni udajmi zo suboru s dodavatelmi, ak taky uz existuje, ak nie, tak ostanu polia v tabulke prazdne, aby sa zadali nove. na konci tlacidlo ulozit, ktore udaje o dodavatelovi zapise. otvaracie hodiny sa edituju na tej istej stranke (cize stranka s editovanim otvaracich hodin splynie s touto strankou). eviduju sa tieto udaje: cofor, firma, mesto, krajina, otvaracie hodiny, sposob nakladky (vyber z moznosti: back, side, back/side) 
5. otvaracie hodiny budu pre vsetkych 7 dni, ale pondelkove sa automaticky skopiruju do utorok-piatok.  v generovanom exceli sa ale vzdy pouziju tie hodiny, ktore vychadzaju na prvy den, ktory je zaskrtnuty v grafikone v tom riadku (cize ak sa lisia hodiny v pondelok a stredu a kamion tam chodi aj v pondelok aj v stredu, tak v generovanom exceli budu pondelkove hodiny)
6. pridat do tabulky stlpcek na typ zastavky: loading P, unloading P, loading E, unloading E, unloading E+loading P, border, cielova vykladka  (cielova vykladka aj border, ak maju nenulove trvanie sa rataju ako praca zamestnanca) - tu potrebujeme aj nejako specifikovat jednotlive rampy v zavode pre kazdeho dodavatela tzn. na ktorej rampe bude v zavode vykladat. Vlozit prosim stlpcek s moznostou vyberu ako pri casti „typ zastavky“ zoznam ramp: 4M1, 4M2,4M3, 1F1, 3P1,3P2,3P3. Niektory dodavatel moze vsak vykladat na viacerych rampach. Napr. dod Mann Hummel 4M1, 4M3
7. pridat do tabulky stlpcek pre typ naklady/vykladky: back, side, back/side
8. pridat moznost pre cely grafikon zadat tieto udaje:
* THIS FLOW WILL START BY A :  string
* HEIGHT OF THE GOODS :         double [m]
* REQUESTED HEIGHT OF THE TRUCK : double [m]
* REQUESTED LENGTH OF THE TRUCK FIELD 1: double [m]
* REQUESTED LENGTH OF THE TRUCK FIELD 2: double [m]
* Km EXPORT: int      
* Km IMPORT: int
9. pridat typ riadka "vykladka v cieli" – Tym riadkom budu vkladane udaje o operaciach v zavode (spodna cervena cast aktualnych grafikonov). bolo by vhodne pridat moznost vyberu zo zoznamu ramp v zavode * zoznam ramp nizsie, 
10. pridat typ riadka "border"
11. pridat tlacidla [+] na konci kazdeho riadka [route], rozdeli jazdu
12. pridat tlacidla [-] na konci kazdej prestavky, odstrani prestavku
13. pridat okrem nazvu grafikonu aj verziu (to by ale mohlo cele spolu tvorit meno suboru - takze toto by som asi neriesil, nech sa Vas subor vola napr. "nazov_grafikonu.grafikon" a exportovany "nazov_grafikonu.xlsx") pridat aj datum aplikacie grafikonu, ktory bude zahrnuty aj v exportovanom exceli
14. pridat nepovinny stlpec freq cofor (int), kde si zadaju svoj kod pre tento stlpec
15. pridat stranku, na ktorej sa daju nahadzovat km pre prechody medzi krajinami:  krajina1, krajina2  pocet kilometrov. tieto udaje sa pouziju ako vychodisko pre vyplnenie tabulky rozpisujucej kilometre podla krajin, ktoru tam uz mate, ta ostava, ale predvyplni sa podla tychto udajov, ale bude sa dat rucne zmenit.

* zoznam ramp v zavode (spodna cervena cast v cielovom bode)
```
Arrival TR31 MON
Arrival TR30 FER
Colne oddelenie
Break time
Departure of PCA
Unloading 4M1
Unloading 1F1
Unloading 4M2
Unloading 3P1
Unloading 4M3
Unloading 3P2
Empties TR74-Montaz
Unloading 3P3
Empties 4M1
Loading 1F1
Empties 4M3
Empties TR72-Zvarovna
4M4 
5D1 
```

poslite mi upraveny katalog poziadaviek, prosim, cim skor a navrh UI by sme presli na nasom stretnuti. dakujem!

**Comment by Kirito-chan** [comment]
Katalóg požiadaviek je hotový, môžete to prosím skontrolovať? @pavelpetrovic 

Vďaka!

**Comment by pavelpetrovic** [comment]
ahojte, hovoril som dnes s dvomi dámami od zadávateľov, keďže sme mali hovor kvôli inému projektu. 
pýtal som sa na tie kódy dní, vravia, že napr. 500 znamená každý deň, takže podľa mňa by bolo najjednoduchšie, aby ste mali jeden súbor, v ktorom by sa dali všetky tieto kódy nastaviť, napr.

124=1,2,4
500=1,2,3,4,5

atď. a všetky možné kódy by tam boli.
s tým, že admin by v prípade potreby zmeny otvoril tento súbor a pridal tam ďalší riadok.
oni nám nejaký východiskový zoznam kódov pošlú.
