### ISSUE TITLE
Čakať na odpoveď od zadávateľa ohľadom našich otázok a prepisu (zadávateľ bol kontaktovaný 12.10 a 16.10)

### ISSUE THREAD

**Issue by foldesi2** [TIS2020-FMFI/rampa#15]

**Comment by foldesi2** [comment]
[Katalóg požiadaviek.docx](https://github.com/TIS2020-FMFI/rampa/files/5402514/Katalog.poziadaviek.docx)

**Comment by pavelpetrovic** [comment]
predtým bol v tomto issue súbor s prvým návrhom KP, teraz ho tu nevidím, zmazali ste ho?
dostali sa informácie z neho do novej verzie? ako to aktuálne vyzerá s novou verziou?

**Comment by foldesi2** [comment]
@pavelpetrovic 
Je to v novej verzii ktorá je uložená na drive, link je v issue katalóg požiadaviek

**Comment by pavelpetrovic** [comment]
tam ale este skoro nic nie je. 
mal som na mysli toto: 
[KP_rampa_stary.docx](https://github.com/TIS2020-FMFI/rampa/files/5443794/KP_rampa_stary.docx)

mam pocit, ze to bolo v tomto issue predtym, ale asi ste to zmazali.

v kazdom pripade tam mate v issues trosku zmatok a ku KP privela issues, naviac niektore duplicitne, len nie su 
zaradene do projektu, takze v projekte ich vidno ako karticku iba raz.

skuste to poupratovat, zmazat, pripadne zatvorit issues, kde uz nic zaujimave nie je a udrzte si jeden issue, kde je linka na posledny platny KP, dopiste ho, skontrolujte a potom ma notifikujte. dakujem.
