### ISSUE TITLE
Vybrať programovací jazyk v ktorom budeme pracovať

### ISSUE THREAD

**Issue by foldesi2** [TIS2020-FMFI/rampa#19]

**Comment by Kirito-chan** [comment]
Ja osobne som buď za Python alebo Javu. Skôr preferujem Javu, ale prispôsobím sa, ak nie všetci ju obľubujú alebo ju ešte nemali :)

**Comment by foldesi2** [comment]
Ja som skôr za Javu, ale python je tiež v pohodičke

**Comment by Us3capp** [comment]
Za mňa radšej Javu

**Comment by barboradurackova** [comment]
Aj ja súhlasím s Javou.

**Comment by Kirito-chan** [comment]
Dobre, tak budeme robiť v Jave.
