### ISSUE TITLE
Požiadať zadávateľa, nech nám pošle nejaký grafikon - excel

### ISSUE THREAD

**Issue by Kirito-chan** [TIS2020-FMFI/rampa#20]
Keďže máme len 3 screenshoty z Teams hovoru toho grafikonu, ktorý je mimochodom integrálnou súčasťou nášho projektu, keďže ho máme vytvoriť, tak by bolo prospešné, aby nám poslali nejaký vzorový grafikon - excel. Napríklad ten, čo nám ukazovali v Teams hovore, ten grafikon laval.

**Comment by pavelpetrovic** [comment]
pridavam iba dalsi z hovoru o tych round-trip / simple trip
![RT_ST](https://user-images.githubusercontent.com/13798920/98169111-f581bb80-1eeb-11eb-95b4-228d5c1215f4.png)
