### ISSUE TITLE
Špecifikácia vonkajších interface-ov

### ISSUE THREAD

**Issue by foldesi2** [TIS2020-FMFI/rampa#22]

**Comment by Kirito-chan** [comment]
Naša aplikácia by mala pracovať s aplikáciou Excel. Keďže budeme pracovať v jazyku Java, tak by sme mohli pracovať s knižnicou Apache POI.  Tu je napríklad dobrý link ako zapisovať do Excelu pomocou tohto modulu, keďže sa nám to bude hodiť: [https://www.codejava.net/coding/how-to-write-excel-files-in-java-using-apache-poi]

Taktiež by sme mohli pracovať s klasickými .txt súbormi, keďže komunikácia s externou databázou je náročnejšia na riadenie a keďže daná firma by mala využívať našu aplikáciu aj po skončení tohto semestra, tak aby mohli údaje ukladať lokálne do počítača a tiež z neho čítať, keďže si chcú nejaké template-y grafikonou ukladať - čo je len jednoduchy formát na zapísanie do súboru. Napr. budú mať uloženy grafikon Laval (milkrun do francúzskeho mesta Laval) napr. v súbore laval.txt, a keď budú v našej appke chcieť zmeniť napr. otváracie hodiny, tak si ho otvoria a ľahko zmenia. Čiže komplexnosť nášho systému si nevyžaduje zložitejšie databázy, ale stačia súbory.

A bude to fungovať na Windowse, bude to desktopová appka.
