### ISSUE TITLE
Vytvoriť UI na stránke moqups

### ISSUE THREAD

**Issue by foldesi2** [TIS2020-FMFI/rampa#24]

**Comment by barboradurackova** [comment]
Urobila som GUI, @Kirito-chan prosím skontroluj to a pridaj komentáre.

https://app.moqups.com/SMct8Jgo6K/edit/page/ad29e969c

**Comment by Kirito-chan** [comment]
Ahoj, tak pozrel som to a skontroloval. Doplnil som tam dalsie stlpce do toho vstupu aj do tabulky ukazky. A tiez pole Miesto a Cas odchodu zo startu.

A potom pridla komentare a vysvetlil co na co sluzi. Tak snad sa to zadavatelovi bude pacit.

Ale uz by to teda malo byt finalne - spravne.

**Comment by Kirito-chan** [comment]
Upravil som GUI na moqups podla rozhovoru s GEFCO, ktory mali minulu stredu. Podla mna som tam dal vsetko co chceli, uz by to mohlo byt finalne. Ale mohol som daco zabudnut. Pouzivajte tento odkaz na priecinok cislo 4: https://app.moqups.com/SMct8Jgo6K/edit/page/a9be75926

Prosim pozrite to @barboradurackova, @foldesi2, @Us3capp :)

**Comment by pavelpetrovic** [comment]
Mohli by ste prosím, na stránku "ukážka" pridať ešte jeden stĺpček "nový čas", do ktorého by používateľ mohol v niektorom stĺpci zadať iný čas, ktorý by sa použil v tom riadku (a v predchádzajúcom riadku v stĺpci "čas odchodu") a potom tlačidlo (napr. celkom hore alebo celkom dole) "prepočítať", ktoré by prerátalo plán tak, že by upravilo ten čas príchodu podľa zadanej hodnoty? 
Dovolí zadať iba neskorší čas, ako je najskorší možný.
Zároveň sa tie nové hodnoty zo stĺpca "nový čas" zapamätajú, takže keď otvorí ukážku znovu, tak tam budú znovu a tiež keď 

Myslím si, že toto Vám pridá minimum práce, ale im to môže výrazne uľahčiť používanie, lebo prvý vygenerovaný itinerár nemusí vyhovovať a niekde sa môže hodiť to presunúť podľa potreby na trochu neskorší termín, predĺžiť prestávku a pod.

A ak by ste chceli byť ešte šikovnejší, tak by ste pridali za každý riadok, ktorý nie je prestávkový, malú linku [+], pomocou ktorej  by ten úsek jazdy mohli rozbiť na dva vložením prestávky do stredu (takto vložené prestávky by mali zasa linku [-], ktorou by sa dali odstrániť). Úplne dokonalé by bolo, keby potom dovolil pomocou tej možnosti "nový čas" tú druhú prestávku aj skrátiť, podľa podmienok v zákone.

Ešte nerozumiem, kedy sa to ukladá do súboru, možno som len niečo prehliadol/nepochopil, nebolo by dobre pridať ešte nejaké tlačidlo "uložiť"?

**Comment by Kirito-chan** [comment]
Už som to upravil.

Upravil som úvodnú stránku, kde po kliknutí na **Vytvoriť grafikon"** tam pridá textové pole, kde zadá názov súboru. Ak nezadá meno súboru, tak ho to ani nepustí ďalej cez tlačidlo Potvrdiť. Keď zadá meno, tak sa mu rozsvieti tlačidlo **Potvrdiť** a vojde na stránku pre zadávanie vstupov.

Tam som pridal do otváracích hodín tlačidlo **Pridaj**, ktoré ho dostane na stránku kde môže zadať otváracie hodiny pre daného dodávateľa (t.j. pre dané **meno zastávky** a **miesto zastávky**, ktoré sú dané v prvých dvoch stĺpcoch). Keď vyplní údaje pre otváracie hodiny a klikne potvrdiť, tak automaticky by to mohlo niekde uložiť do súboru, pre dvojicu **meno zastávky: miesto zastávky** priradí čas otváracích hodín, aby keď nabudúce budú pridávať Otváracie hodiny pre daného dodávateľa, tak po stlačení tlačidla **Pridaj**, ktoré je v stĺpci Otváracie hodiny, tak ho to nepreklikne na tú stranku, kde by ich mal zadať, ale automaticky predvyplní. Bude však treba potom poriešiť nejaký spôsob, kde bude môcť odstraňovať/prepisovať uložené údaje. To by som robil až na konci keď všetko bude fičať, lebo je to taká naviac feature, čo im celkom pomôže.

Tiež pridal nový stĺpec "nový čas" do Ukážky ako písal p. Petrovič o komentár vyššie, ktorý bude upravovať čas príchodu v danom riadku. A tiež aj tlačidlo "prepočítať" a tiež tlačidlá plus a mínus ku riadkom, čo nie sú prestávkové v tabuľke Ukážky (viď Petrovičov komentár, čo to má robiť).

A tiež tlačidlo Uložiť na stránke zadávania vstupov pre grafikon, aby si mohli uložiť zadané údaje a potom ich načítať keď budú niekedy potrebovať.

Tak to pozrite prosím: @barboradurackova, @foldesi2, @Us3capp a aj p. Petrovič, ak budete mať čas @pavelpetrovic :)

Vďaka!
