### ISSUE TITLE
Vytvoriť UML Component diagram

### ISSUE THREAD

**Issue by foldesi2** [TIS2020-FMFI/rampa#26]

**Comment by foldesi2** [comment]
Diagram by sa mohol skladať z cca týchto častí :

GUI
vytvorenie excelu - planu
vypoctovy modul
vyexportovat do suboru
vstupy ulozitelne
vstupy nacitatelne
vstupy sa daju delit mozno

**Comment by pavelpetrovic** [comment]
date k tomu aj nejake lepsie nazvy a kratky popis, co ktory komponent robi, prosim?

**Comment by Kirito-chan** [comment]
Tak uz som urobil nejaky navrh toho component diagramu, mozte to pozriet:
https://drive.google.com/file/d/1rUOlM_zz-bfXVZUWqZyjka0sbCmL16P7/view?usp=sharing

V skratke o komponentoch:
- **GUI Creator**:  vytvára GUI
- **Inputs Saving**: ukladá dáta z inputov do súboru, čiže keď sa uloží grafikon
- **Inputs Loading**: naťahuje dáta zo súboru (t.j. predtým vytvorených grafikonov)
- **Editor of a Table**: API, ktoré bude zodpovedné za editovanie tabuľky
- **Sample Display**: zobrazuje ukážku
- **New Time Recalculation**: prepočítáva novo zadané údaje do ukážky
- **Excel Export**: exportuje dáta do excel tabuľky (t.j. výsledneho grafikonu)
- **Adding Opening Hours**: pridáva otváracie hodiny pre daného dodávateľa
- **Opening Hours Saving**: pre daného dodávateľa ukladá otváracie hodiny do súboru
-  **Configuration of Parameters**: konfiguruje fixné parametre ako napr. povinná dĺžka oddychu podľa zákona medzi šoférovaním (krátku 45min aj dlhú 11hod) 
- **Configuration**: konfiguračný súbor
- **Graficons**: súbor s uloženými grafikonmi
- **Supplier Opening Hours**: súbor, kde pre dvojicu "Meno zastávky": "Miesto zastávky" je priradený údaj otváracích hodín. T.j. každé odberné miesto u dodávateľa bude mať v tomto súbore uložené svoje otváracie hodiny.
