### ISSUE TITLE
Prechod medzi oknami v programe, otváranie zatváranie

### ISSUE THREAD

**Issue by foldesi2** [TIS2020-FMFI/rampa#31]

**Comment by foldesi2** [comment]
Môj návrh vytvárania je cez Stage ktorý sa vytvorí pri spustení a pod Stage patria jednotlivé Scenes, každá má svoju funkciu (kde sa špecifikuje jednotlivé okno) a otvárajú sa napríklad onclick buttonom (alebo hocičím iným ale v našom programe to bude asi jedine onclick button) spôsobom že sa zavrie pôvodný stage (stage.close()) a otvorí sa nový ( Stage scena = new Stage(); stage.close(), stage_create(scena)) kde stage_create bude nami vytvorená funkcia kt. bude iná pre každé nové okno. Bližšie to mám špecifikované v java súbore ktorý doladím a dám sem ako prílohu

**Comment by Kirito-chan** [comment]
Vyborne, takze cez stages to budeme robit, vdaka za research :)
