### ISSUE TITLE
Vytvoriť GUI v Jave podla Moqups

### ISSUE THREAD

**Issue by Kirito-chan** [TIS2020-FMFI/rampa#48]
vytvorit vsetky obrazovky z GUI podla moqups

**Comment by Kirito-chan** [comment]
uz vytvorene

**Comment by Kirito-chan** [comment]
uz je vytvorene cele GUI

**Comment by pavelpetrovic** [comment]
dobry den! ako vyzerate s projektom? neskusite si dohodnut stretnutie s GEFCO niekedy buduci tyzden na predvedenie hotoveho projektu, aby to mali cas este otestovat?
